# CRD creator service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $CRD_SERVICE_ACCOUNT
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $CRD_SERVICE_ACCOUNT-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  - deployments
  verbs:
  - get
  - patch
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - list
  - patch
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list","create","patch"]
- apiGroups: ["*"]
  resources: ["serviceaccounts","pods"]
  verbs: ["get","list","create","patch"]
- apiGroups:
  - pxc.percona.com
  resources:
  - perconaxtradbclusters
  - perconaxtradbclusters/status
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $CRD_SERVICE_ACCOUNT-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $CRD_SERVICE_ACCOUNT-role
subjects:
- kind: ServiceAccount
  name: $CRD_SERVICE_ACCOUNT
  namespace: $NAMESPACE
#Operator service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $OPERATOR_SERVICE_ACCOUNT
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: $OPERATOR_SERVICE_ACCOUNT-role
rules:
- apiGroups:
  - pxc.percona.com
  resources:
  - perconaxtradbclusters
  - perconaxtradbclusters/status
  - perconaxtradbclusterbackups
  - perconaxtradbclusterbackups/status
  - perconaxtradbclusterrestores
  - perconaxtradbclusterrestores/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - configmaps
  - services
  - persistentvolumeclaims
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - certmanager.k8s.io
  - cert-manager.io
  resources:
  - issuers
  - certificates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: $OPERATOR_SERVICE_ACCOUNT-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $OPERATOR_SERVICE_ACCOUNT-role
subjects:
- kind: ServiceAccount
  name: $OPERATOR_SERVICE_ACCOUNT
  namespace: $NAMESPACE

