x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false
  images:
    '':
      properties:
        operator.image.registry:
          type: REGISTRY
        operator.image.repository:
          type: REPO_WITHOUT_REGISTRY
        operator.image.tag:
          type: TAG
    pxc80:
      properties:
        pxc80.image.registry:
          type: REGISTRY
        pxc80.image.repository:
          type: REPO_WITHOUT_REGISTRY
        pxc80.image.tag:
          type: TAG
    pxc57:
      properties:
        pxc57.image.registry:
          type: REGISTRY
        pxc57.image.repository:
          type: REPO_WITHOUT_REGISTRY
        pxc57.image.tag:
          type: TAG
    pxc80backup:
      properties:
        pxc80backup.image.registry:
          type: REGISTRY
        pxc80backup.image.repository:
          type: REPO_WITHOUT_REGISTRY
        pxc80backup.image.tag:
          type: TAG
    pxc57backup:
      properties:
        pxc57backup.image.registry:
          type: REGISTRY
        pxc57backup.image.repository:
          type: REPO_WITHOUT_REGISTRY
        pxc57backup.image.tag:
          type: TAG
    haproxy:
      properties:
        haproxy.image.registry:
          type: REGISTRY
        haproxy.image.repository:
          type: REPO_WITHOUT_REGISTRY
        haproxy.image.tag:
          type: TAG
    proxysql:
      properties:
        proxysql.image.registry:
          type: REGISTRY
        proxysql.image.repository:
          type: REPO_WITHOUT_REGISTRY
        proxysql.image.tag:
          type: TAG
    logcollector:
      properties:
        logcollector.image.registry:
          type: REGISTRY
        logcollector.image.repository:
          type: REPO_WITHOUT_REGISTRY
        logcollector.image.tag:
          type: TAG
  clusterConstraints:
    resources:
    - replicas: 3
      requests:
        cpu: 2
        memory: 5Gi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_MINIMUM_NODE_COUNT
          minimumNodeCount: 3
    istio:
      type: UNSUPPORTED

properties:
  name:
    type: string
    title: Percona Xtradb Cluster name
    x-google-marketplace:
      type: NAME
    maxLength: 22
  namespace:
    type: string
    title: Target namespace
    x-google-marketplace:
      type: NAMESPACE
  operator.serviceAccountName:
    type: string
    title: Percona Xtradb Cluster Operator service account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Operator essential privileges
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups:
              - pxc.percona.com
              resources:
              - perconaxtradbclusters
              - perconaxtradbclusters/status
              - perconaxtradbclusterbackups
              - perconaxtradbclusterbackups/status
              - perconaxtradbclusterrestores
              - perconaxtradbclusterrestores/status
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
            - apiGroups:
              - ""
              resources:
              - pods
              - pods/exec
              - pods/log
              - configmaps
              - services
              - persistentvolumeclaims
              - secrets
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
            - apiGroups:
              - apps
              resources:
              - deployments
              - replicasets
              - statefulsets
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
            - apiGroups:
              - batch
              resources:
              - jobs
              - cronjobs
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
            - apiGroups:
              - policy
              resources:
              - poddisruptionbudgets
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
            - apiGroups:
              - certmanager.k8s.io
              - cert-manager.io
              resources:
              - issuers
              - certificates
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
              - deletecollection
  CDRJobServiceAccount:
    type: string
    title: Service account used by CRDs deployer
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          CRD install essentials
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups:
              - ""
              resources:
              - pods
              - pods/exec
              - serviceaccounts
              verbs:
              - get
              - list
              - patch
              - delete
            - apiGroups:
              - apps
              resources:
              - deployments
              verbs:
              - get
              - patch
            - apiGroups:
              - batch
              resources:
              - jobs
              - deployments
              verbs:
              - get
              - patch
            - apiGroups:
              - app.k8s.io
              resources:
              - applications
              verbs:
              - get
            - apiGroups: ["rbac.authorization.k8s.io"]
              resources: ["clusterroles","clusterrolebindings"]
              verbs: ["list", "get", "patch"]
            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions"]
              verbs: ["get","list","create","patch"]
            - apiGroups: ["*"]
              resources: ["serviceaccounts"]
              verbs: ["get","list","create"]
            - apiGroups:
              - pxc.percona.com
              resources:
              - perconaxtradbclusters
              - perconaxtradbclusters/status
              verbs:
              - get
              - create
              - update
              - patch
              - delete
  deployerHelm.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  pxc.version:
    type: string
    x-google-marketplace:
      type: STRING
    default: "$PXC_80"
    title: Percona Xtradb Cluster version
    description: Choose between 5.7 and 8.0 builds
    enum:
    - "$PXC_80"
    - "$PXC_57"
  pxc.datadir.size:
    type: string
    x-google-marketplace:
      type: STRING
    default: 20Gi
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'
    title: Percona Xtradb Cluster datadir size
    description: Volume size for DB data dir
  pxc.replicas:
    type: integer
    title: Percona Xtradb Cluster node quantity
    description: Number of nodes in Percona Xtradb Cluster. In order to maintain cluster safe configuration the number of nodes should be odd and equal or less than nuber of your Kubernetes cluster nodes
    default: 3
    enum:
    - 1
    - 3
    - 5
  serviceType:
    type: string
    x-google-marketplace:
      type: STRING
    default: PublicLB
    enum:
    - PublicLB
    - InternalLB
    - ClusterIP
    title: Percona Xtradb Cluster application service type
    description: The type of the kubernetes network service object for accessing Percona Xtradb Cluster database


required:
- name
- namespace
- operator.serviceAccountName
- pxc.version
- pxc.datadir.size
- pxc.replicas
- serviceType
