
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "psmdb-operator.CRConfigMap" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: crd-configmap
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "files/custom-resource/*.yaml" }}
  {{ base $path }}: |-
  {{- tpl ($root.Files.Get $path) $root | nindent 4}}
  {{- end -}}
