apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "psmdb-operator.fullname" . }}
  labels:
{{ include "psmdb-operator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "psmdb-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "psmdb-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.operator.image.registry }}/{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | trunc 5 }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - percona-server-mongodb-operator
          env:
            - name: WATCH_NAMESPACE
              value: {{ default .Release.Namespace .Values.watchNamespace }}
            - name: OPERATOR_NAME
              value: {{ default "percona-server-mongodb-operator" .Values.operatorName }}
            - name: RESYNC_PERIOD
              value: "{{ .Values.env.resyncPeriod }}"
            - name: LOG_VERBOSE
              value: "{{ .Values.env.logVerbose }}"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: metrics
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
